######################################################################
# Automatically generated by qmake (3.0) Tue Mar 27 15:30:20 2018
######################################################################

TEMPLATE = app
TARGET = QtQuickApp

QT += \
    gui \
    widgets \
    quick \
    qml

INCLUDEPATH += .

CONFIG += qtquickcompiler

# Input
SOURCES += main.cpp

HEADERS +=

RESOURCES += qml.qrc
